name: SaraToggle
version: 1.0.0
api-version: 1.13
main: net.azisaba.saratoggle.SaraToggle
depend:
  - AziPluginMessaging
commands:
  gamingsara:
    description: "Toggles the gaming sara"
    permission: saratoggle.gamingsara
  sara:
    description: "Toggles the sara"
    permission: saratoggle.sara
